### ISSUE TITLE
To rework on matching result

### ISSUE THREAD

**Issue by motss** [reallyland/url-observer#3]
## Proposal

* [x] To consider use `params` in favor of `matches` (#5)
* [x] To include matching route/ pathname/ URL (#6)
* [x] To include matching tail (#2)

**Comment by motss** [comment]
Closing at 92591f5
